language: node_js
node_js:
  - 14
cache: npm
before_install: git pull
before_script: npm update
branches:
  except:
    - main
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: ${GITHUB_TOKEN} # Your GitHub token set in Travis CI console
  target_branch: main
  on:
    branch: dev # Your GitHub repo default branch
env:
  TESTVAR: ${TESTVAR}
