language: node_js
node_js:
  - 14
cache: npm
before_script: npm update
branches:
  except:
    - master
after_success:
  - curl
    https://gist.githubusercontent.com/lxhunter/758e1e3041d7ec7aec3814018d781e29/raw/merge.sh
    | bash
